#############################################################################
##
##  Groups.gd                                                 Blocks package
##
##  Copyright 2013,      Mohamed Barakat, University of Kaiserslautern
##
##  Declaration stuff for groups.
##
#############################################################################

####################################
#
# attributes:
#
####################################

DeclareAttributeWithDocumentation( "SerreCharacteristicSubgroup",
        IsGroup,
        [ "Computes the characteristic subgroup of <A>G</A>",
          "generated by the involutions and the squares.",
          "<#Include Label=\"SerreCharacteristicSubgroup\">" ],
        "a subgroup of <A>G</A>",
        "G",
        [ "Groups", "Attributes" ],
        rec( function_label := "for IsGroup" )
        );

DeclareAttributeWithDocumentation( "SerreFactorGroup",
        IsGroup,
        [ "Computes the factor group modulo of <A>G</A>",
          "<C>SerreCharacteristicSubgroup</C><M>(</M><A>G</A><M>)</M>",
          "(&see; <Ref Attr=\"SerreCharacteristicSubgroup\" Label=\"for IsGroup\"/>).",
          "<#Include Label=\"SerreFactorGroup\">" ],
        "a factor group of <A>G</A>",
        "G",
        [ "Groups", "Attributes" ],
        rec( function_label := "for IsGroup" )
        );

DeclareAttributeWithDocumentation( "NumberOfQuadraticEquationsOfUnitaryGroup",
        IsGroup,
        [ "Computes the number of quadratic equations",
          "defining the unitary group of the group ring of <A>G</A>",
          "in characteristic <M>2</M>.",
          "<#Include Label=\"NumberOfQuadraticEquationsOfUnitaryGroup\">" ],
        "a nonnegative integer",
        "G",
        [ "Groups", "Attributes" ],
        rec( function_label := "for IsGroup" )
        );

DeclareAttributeWithDocumentation( "DimensionOfUnitaryGroup",
        IsGroup,
        [ "Computes the dimension of the unitary group",
          "of the group ring of <A>G</A> in characteristic <M>2</M>.",
          "<#Include Label=\"DimensionOfUnitaryGroup\">" ],
        "a nonnegative integer",
        "G",
        [ "Groups", "Attributes" ],
        rec( function_label := "for IsGroup" )
        );

####################################
#
# global functions and operations:
#
####################################

# basic operations:

DeclareOperationWithDocumentation( "DefectGroup",
        [ CategoryCollections(IsMultiplicativeElementWithInverse), IsInt ],
        [ "Computes the defect <A>p</A>-group of a representative",
          "<M>g=</M><C>Representative</C><M>(</M><A>K</A><M>)</M>",
          "of the conjugacy class <A>K</A><M>=g^G</M> as a subgroup of",
          "<M>G=</M><C>ActingDomain</C><M>(</M><A>K</A><M>)</M>.",
          "<#Include Label=\"DefectGroup_code:cc\">",
          "<#Include Label=\"DefectGroup:cc\">" ],
        "a subgroup of <M>G</M>",
        "K, p",
        [ "Groups", "Operations" ]
        );
